**BLADE-RF SPECTRUM SENSING**

In [11]:
import numpy as np

**Building Sample Covariance Matrix (SCM)**

In [12]:
rx_signal = np.array([1,2,3,4,5,6,7,8,9,10]) # Insert here according to the true received signal vector
print("rx_signal = ", rx_signal)

rx_signal =  [ 1  2  3  4  5  6  7  8  9 10]


In [13]:
N = len(rx_signal) # Number of samples present in the received signal vector
print("The length of rx_signal is: ", N)

The length of rx_signal is:  10


In [14]:
# The following steps are taken in order to build the received signal matrix from the received signal vector. Basically, it will divide the whole received signal vector in segments with each one being positioned in each line of the received signal matrix;
num_segments = 5 # We must vary here, and identify the best one, verifing the influence of the number of segments in the performance (i.e., analyze the influence of this value in the Pd, for example);
len_segment = N // num_segments # Number of samples present in each segment.

In [15]:
rx_signal_matrix = np.reshape(rx_signal, (num_segments, len_segment)) # Building the received signal matrix based on the received signal vector. This step is necessary because the SCM requires this.
print("The receiver signal matrix is equal to ", rx_signal_matrix)

The receiver signal matrix is equal to  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [16]:
scm = (rx_signal_matrix @ rx_signal_matrix.T) / num_segments # Sample Covariance Matrix (SCM) computation.
print("The resultant Sample Covariance Matrix is equal to ", scm)

The resultant Sample Covariance Matrix is equal to  [[ 1.   2.2  3.4  4.6  5.8]
 [ 2.2  5.   7.8 10.6 13.4]
 [ 3.4  7.8 12.2 16.6 21. ]
 [ 4.6 10.6 16.6 22.6 28.6]
 [ 5.8 13.4 21.  28.6 36.2]]


**Building Pietra-Ricci Index Detector (PRIDe)**

In [17]:
r = scm.flatten().reshape(-1,1) # This vector is build by stacking all columns of the SCM;
T_pride = np.sum(np.abs(r)) / np.sum(np.abs(r - np.mean(r))) # PRIDe test statistic computation.
print("A estatística de teste do PRIDe é: ", T_pride)

A estatística de teste do PRIDe é:  1.5885416666666667
