In [24]:
import numpy as np

In [25]:
rx_signal = np.array([1,2,3,4,5,6,7,8,9,10]) # insert here according to the true received signal
print("rx_signal = ", rx_signal)

rx_signal =  [ 1  2  3  4  5  6  7  8  9 10]


In [26]:
N = len(rx_signal) # Number of samples present in the received signal
print("The length of rx_signal is: ", N)

The length of rx_signal is:  10


In [27]:
num_segments = 5 # We must vary here, and identify the best one, verifing the influence of the number of segments in the performance (i.e., analyze the influence of this value in the Pd, for example)
len_segment = N // num_segments # Number of samples present in each segment

In [28]:
rx_signal_matrix = np.reshape(rx_signal, (num_segments, len_segment)) # Building the received signal matrix based on the received signal vector
print("The receiver signal matrix is equal to ", rx_signal_matrix)

The receiver signal matrix is equal to  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [29]:
scm = (rx_signal_matrix @ rx_signal_matrix.T) / num_segments #
print("The resultant Sample Covariance Matrix is equal to ", scm)

The resultant Sample Covariance Matrix is equal to  [[ 1.   2.2  3.4  4.6  5.8]
 [ 2.2  5.   7.8 10.6 13.4]
 [ 3.4  7.8 12.2 16.6 21. ]
 [ 4.6 10.6 16.6 22.6 28.6]
 [ 5.8 13.4 21.  28.6 36.2]]
